---

- name: systemctl daemon-reload
  listen: service modified
  service:
    daemon_reload: true

- name: caddy restart
  listen: service modified
  service:
    name: caddy
    state: restarted

- name: caddy reload
  service:
    name: caddy
    state: reloaded

# vim: set et st=2 sts=2 sw=2 ts=2:
