---
- name: install mnamer
  pip:
    state: latest
    name: mnamer

- name: configure mnamer
  template:
    src: mnamer-v2.json.j2
    dest: "{{ rtorrent_mnamer_home }}/.mnamer-v2.json"
    owner: "{{ rtorrent_user_name }}"
    group: "{{ rtorrent_group_name }}"
    mode: 0644 


# vim: set et st=2 sts=2 sw=2 ts=2:
