---
- name: download caddy for arm
  when: ansible_architecture == 'aarch64'
  get_url:
    url: https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com%2Fcaddy-dns%2Fgandi
    dest: '{{ caddy_bin_path }}'
    mode: '0755'
    force: true

- name: download caddy for x86
  when: ansible_architecture == 'x86_64'
  get_url:
    url: https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fgandi
    dest: '{{ caddy_bin_path }}'
    mode: '0755'
    force: true

- name: create caddy group
  group:
    name: '{{ caddy_group_name }}'
    gid: '{{ caddy_group_id }}'
    system: true

- name: create caddy user
  user:
    name: '{{ caddy_user_name }}'
    uid: '{{ caddy_user_id | int }}'
    group: '{{ caddy_group_id | int }}'
    home: '{{ caddy_user_home }}'
    create_home: true
    shell: '/usr/sbin/nologin'
    system: true

- name: create systemd service
  template:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    mode: 0644
  notify: service modified

- name: create config directory
  file:
    path: '{{ caddy_config_path }}'
    state: directory
    owner: '{{ caddy_user_name }}'
    group: '{{ caddy_group_name }}'
    mode: 0755

- name: create vhosts directory
  file:
    path: '{{ caddy_config_path }}/vhosts'
    state: directory
    owner: '{{ caddy_user_name }}'
    group: '{{ caddy_group_name }}'
    mode: 0755

- name: create log directory
  file:
    path: '{{ caddy_log_path }}'
    state: directory
    owner: '{{ caddy_user_name }}'
    group: '{{ caddy_group_name }}'
    mode: 0755

- name: copy caddyfile
  copy:
    src: caddyfile
    dest: '{{ caddy_config_path }}/caddyfile'
    owner: '{{ caddy_user_name }}'
    group: '{{ caddy_group_name }}'
    mode: 0644
  notify: caddy restart

- name: enable and start caddy service
  service:
    name: 'caddy.service'
    state: started
    enabled: true

- include_tasks: vhosts.yml
  vars:
    vhost: '{{ caddy_vhost_defaults | combine(vhost_) }}'
  loop: '{{ caddy_vhosts }}'
  loop_control:
    loop_var: vhost_

# vim: set et st=2 sts=2 sw=2 ts=2:
