---
- name: download kiwix for arm
  when: ansible_architecture == 'aarch64'
  unarchive:
    src: https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-aarch64.tar.gz
    dest: /tmp
    remote_src: yes

- name: download kiwix for x86
  when: ansible_architecture == 'x86_64'
  unarchive:
    src: https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
    dest: /tmp
    remote_src: yes

- name: install kiwix
  shell: "mv /tmp/kiwix-tools_linux-*/kiwix-* /usr/local/bin"

- name: create kiwix group
  group:
    name: '{{ kiwix_group_name }}'
    system: true

- name: create kiwix user
  user:
    name: '{{ kiwix_user_name }}'
    group: '{{ kiwix_group_name }}'
    home: '{{ kiwix_user_home }}'
    create_home: true
    shell: '/usr/sbin/nologin'
    system: true
    skeleton: false

- name: create systemd service
  template:
    src: kiwix.service
    dest: /etc/systemd/system/kiwix.service
    mode: 0644
  notify: service modified

- name: enable and start kiwix service
  service:
    name: 'kiwix.service'
    state: started
    enabled: true

# vim: set et st=2 sts=2 sw=2 ts=2:
