---
- name: install pacman packages
  package:
    name: vim,zsh,git,sudo,nmap,mtr,ansible,certbot,python,python-pip,openssh,docker,docker-compose
    state: present

- name: create wheel group
  group:
      name: wheel
      state: present

- name: create docker group
  group:
      name: docker
      state: present

- name: install sudo config
  copy:
    src: etc/sudo/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: create group shepard
  group:
      name: shepard
      state: present

- name: create user shepard
  user:
    name: shepard
    shell: /bin/zsh
    groups: wheel,shepard,docker


- name: copy ssh pubkey for shepard
  authorized_key:
    user: shepard
    state: present
    key: https://github.com/obynio.keys

- name: update sshd_config
  copy:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: reload sshd
  service:
    name: sshd
    state: reloaded
    enabled: true

- name: reload docker
  service:
    name: docker
    state: reloaded
    enabled: true

# vim: set et st=2 sts=2 sw=2 ts=2:
