---
- name: setup locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items:
    - en_US.UTF-8
    - fr_FR.UTF-8

- name: set timezone to paris
  timezone:
    name: Europe/Paris

- name: add sources.list
  template:
    src: 'sources.list'
    dest: '/etc/apt/sources.list'
    mode: 0644
  notify: apt update

- name: add ansible repository gpg key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
  notify: apt update

- name: add ansible repository for buster
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main
    state: present
    filename: ansible

- name: install basic packages
  apt:
    state: latest
    name:
      - zsh
      - vim
      - git
      - htop
      - curl
      - sudo
      - strace
      - tree
      - zip
      - unzip
      - dnsutils
      - traceroute
      - mtr
      - ansible

- name: create group shepard
  group:
      name: shepard
      state: present

- name: create user shepard
  user:
    name: shepard
    shell: /bin/zsh
    groups: sudo,shepard

- import_tasks: prezto.yml
  vars:
    user: shepard

- name: disable swapiness
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: yes

- name: copy ssh pubkey for shepard
  authorized_key:
    user: shepard
    state: present
    key: https://github.com/obynio.keys

- name: update sshd_config
  copy:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: reload sshd
  service:
    name: sshd
    state: reloaded
    enabled: true

# vim: set et st=2 sts=2 sw=2 ts=2:
