---
- name: create traefik directory
  file:
    path: /srv/docker/traefik
    state: directory
    owner: root 
    group: docker

- name: creating acme.json directory
  file:
    path: /srv/docker/traefik/acme.json
    state: touch
    mode: 0600

- name: adding traefik configuration
  template:
    src: traefik.yml
    dest: /srv/docker/traefik/traefik.yml
    mode: 0600

- name: creating the dedicated network
  docker_network:
    name: http

- name: launching traefik container
  docker_container:
    name: traefik
    image: traefik:2.2
    restart_policy: unless-stopped
    networks_cli_compatible: true
    recreate: true
    networks:
      - name: http
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/docker/traefik/traefik.yml:/traefik.yml
      - /srv/docker/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      GANDIV5_API_KEY: "{{ traefik_gandikey }}"

# vim: set et st=2 sts=2 sw=2 ts=2:
