---

- name: systemctl daemon-reload
  listen: service modified
  service:
    daemon_reload: true

- name: systemctl restart calibre
  listen: service modified
  service:
    name: calibre
    state: restarted
    enabled: true

# vim: set et st=2 sts=2 sw=2 ts=2:
